### ISSUE TITLE
Swift Version

### ISSUE THREAD

**Issue by thomasbaldwin** [mechaman/CustomSearchControllerObjc#1]
Hey thanks for creating this, it's super useful. However, I've been struggling to try and convert you're code into Swift. If you created another branch for Swift, I'm sure a lot of other people like myself would find it extremely helpful

**Comment by mechaman** [comment]
Hey thomasbaldwin,
I can have that up by the end of this week. :)

**Comment by thomasbaldwin** [comment]
Thanks! @mechaman

**Comment by mechaman** [comment]
Hey thomasbaldwin,

Sorry for the major delay. I am job hunting right now and its taking a lot of time!
Fortunately, I got it working in Swift. If you still need it here is a link:
https://github.com/mechaman/CustomSearchControllerSwift

Enjoy!

**Comment by thomasbaldwin** [comment]
@mechaman Thanks a lot man!
